[
    {
        "id": 200,
        "title": "Advancements in AI and Machine Learning",
        "description": "Explore the latest breakthroughs in AI and machine learning.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Artificial Intelligence",
        "published_date": "2023-09-16",
        "author": "John Smith",
        "tags": ["AI", "Machine Learning", "Technology"],
        "likes": 120,
        "comments": 25
    },
    {
        "id": 201,
        "title": "5G Revolution: Transforming Connectivity",
        "description": "Learn how 5G technology is revolutionizing the way we connect.",
        "img": "https://i.ibb.co/r5C1y2S/tech3.jpg",
        "category": "Technology",
        "subcategory": "Telecommunications",
        "published_date": "2023-09-15",
        "author": "Emily Brown",
        "tags": ["5G", "Connectivity", "Telecom"],
        "likes": 95,
        "comments": 18
    },
    {
        "id": 202,
        "title": "The Future of Quantum Computing",
        "description": "Discover the potential of quantum computing in solving complex problems.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Quantum Computing",
        "published_date": "2023-09-14",
        "author": "David Anderson",
        "tags": ["Quantum Computing", "Technology"],
        "likes": 150,
        "comments": 30
    },
    {
        "id": 203,
        "title": "Cybersecurity Best Practices for 2023",
        "description": "Stay safe online with the latest cybersecurity tips and practices.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Cybersecurity",
        "published_date": "2023-09-13",
        "author": "Sarah Johnson",
        "tags": ["Cybersecurity", "Online Safety"],
        "likes": 80,
        "comments": 12
    },
    {
        "id": 204,
        "title": "Robotics and Automation in Industry",
        "description": "Explore how robotics is transforming industries worldwide.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Robotics",
        "published_date": "2023-09-12",
        "author": "Michael Clark",
        "tags": ["Robotics", "Automation", "Technology"],
        "likes": 110,
        "comments": 20
    },
    {
        "id": 205,
        "title": "The Rise of Augmented Reality",
        "description": "Discover the applications and potential of augmented reality.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Augmented Reality",
        "published_date": "2023-09-11",
        "author": "Jennifer Lee",
        "tags": ["Augmented Reality", "Technology"],
        "likes": 130,
        "comments": 22
    },
    {
        "id": 206,
        "title": "Blockchain: Beyond Cryptocurrency",
        "description": "Explore the diverse uses of blockchain technology.",
        "img": "https://i.ibb.co/r5C1y2S/tech3.jpg",
        "category": "Technology",
        "subcategory": "Blockchain",
        "published_date": "2023-09-10",
        "author": "Daniel White",
        "tags": ["Blockchain", "Technology"],
        "likes": 100,
        "comments": 15
    },
    {
        "id": 207,
        "title": "The Future of Electric Vehicles",
        "description": "Discover the latest developments in electric vehicle technology.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Electric Vehicles",
        "published_date": "2023-09-09",
        "author": "Lisa Davis",
        "tags": ["Electric Vehicles", "Technology"],
        "likes": 90,
        "comments": 14
    },
    {
        "id": 208,
        "title": "Space Exploration: Mars Missions",
        "description": "Learn about the latest missions to explore Mars.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Space Exploration",
        "published_date": "2023-09-08",
        "author": "Robert Smith",
        "tags": ["Space Exploration", "Mars", "Technology"],
        "likes": 70,
        "comments": 10
    },
    {
        "id": 209,
        "title": "Green Tech: Sustainable Innovations",
        "description": "Explore the sustainable technologies shaping our future.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Sustainability",
        "published_date": "2023-09-07",
        "author": "Emma Turner",
        "tags": ["Green Technology", "Sustainability", "Technology"],
        "likes": 85,
        "comments": 16
    },
    {
        "id": 210,
        "title": "The Evolution of AI in Healthcare",
        "description": "Discover how AI is revolutionizing healthcare.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Artificial Intelligence",
        "published_date": "2023-09-06",
        "author": "Alex Johnson",
        "tags": ["AI", "Healthcare", "Technology"],
        "likes": 120,
        "comments": 25
    },
    {
        "id": 211,
        "title": "Futuristic Wearable Gadgets",
        "description": "Explore the latest wearable technology trends.",
        "img": "https://i.ibb.co/r5C1y2S/tech3.jpg",
        "category": "Technology",
        "subcategory": "Wearable Technology",
        "published_date": "2023-09-05",
        "author": "Sophia Martinez",
        "tags": ["Wearable Tech", "Technology"],
        "likes": 95,
        "comments": 18
    },
    {
        "id": 212,
        "title": "AI in Financial Services",
        "description": "Discover how AI is transforming the finance industry.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Artificial Intelligence",
        "published_date": "2023-09-04",
        "author": "James Wilson",
        "tags": ["AI", "Finance", "Technology"],
        "likes": 150,
        "comments": 30
    },
    {
        "id": 213,
        "title": "The Future of 3D Printing",
        "description": "Explore the possibilities of 3D printing in manufacturing.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "3D Printing",
        "published_date": "2023-09-03",
        "author": "Michelle Taylor",
        "tags": ["3D Printing", "Manufacturing", "Technology"],
        "likes": 110,
        "comments": 20
    },
    {
        "id": 214,
        "title": "Innovations in Renewable Energy",
        "description": "Learn about the latest advancements in renewable energy technology.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Renewable Energy",
        "published_date": "2023-09-02",
        "author": "Paul Robinson",
        "tags": ["Renewable Energy", "Technology"],
        "likes": 130,
        "comments": 22
    },
    {
        "id": 215,
        "title": "The Future of Space Travel",
        "description": "Explore the possibilities of commercial space travel.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Space Exploration",
        "published_date": "2023-09-01",
        "author": "Laura Adams",
        "tags": ["Space Travel", "Technology"],
        "likes": 100,
        "comments": 15
    },
    {
        "id": 216,
        "title": "Smart Cities: Building the Future",
        "description": "Discover how technology is transforming urban living.",
        "img": "https://i.ibb.co/r5C1y2S/tech3.jpg",
        "category": "Technology",
        "subcategory": "Smart Cities",
        "published_date": "2023-08-31",
        "author": "William Turner",
        "tags": ["Smart Cities", "Urban Technology", "Technology"],
        "likes": 90,
        "comments": 14
    },
    {
        "id": 217,
        "title": "The Impact of Biotechnology",
        "description": "Explore the influence of biotechnology on healthcare and beyond.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Biotechnology",
        "published_date": "2023-08-30",
        "author": "Linda Davis",
        "tags": ["Biotechnology", "Healthcare", "Technology"],
        "likes": 70,
        "comments": 10
    },
    {
        "id": 218,
        "title": "The Future of Virtual Reality",
        "description": "Discover the latest VR developments and applications.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Virtual Reality",
        "published_date": "2023-08-29",
        "author": "Chris Anderson",
        "tags": ["Virtual Reality", "Technology"],
        "likes": 85,
        "comments": 16
    },
    {
        "id": 219,
        "title": "Artificial Intelligence in Gaming",
        "description": "Explore how AI is shaping the gaming industry.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Artificial Intelligence",
        "published_date": "2023-08-28",
        "author": "Michael Garcia",
        "tags": ["AI", "Gaming", "Technology"],
        "likes": 120,
        "comments": 25
    },
    {
        "id": 220,
        "title": "The Future of Autonomous Vehicles",
        "description": "Learn about the advancements in autonomous vehicle technology.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Autonomous Vehicles",
        "published_date": "2023-08-27",
        "author": "Daniel Smith",
        "tags": ["Autonomous Vehicles", "Technology"],
        "likes": 95,
        "comments": 18
    },
    {
        "id": 221,
        "title": "Nanotechnology: Tiny Tech with Big Potential",
        "description": "Discover the applications of nanotechnology in various industries.",
        "img": "https://i.ibb.co/r5C1y2S/tech3.jpg",
        "category": "Technology",
        "subcategory": "Nanotechnology",
        "published_date": "2023-08-26",
        "author": "Sarah Adams",
        "tags": ["Nanotechnology", "Technology"],
        "likes": 150,
        "comments": 30
    },
    {
        "id": 222,
        "title": "The Future of Space Exploration",
        "description": "Explore upcoming missions and plans for space exploration.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Space Exploration",
        "published_date": "2023-08-25",
        "author": "Robert Johnson",
        "tags": ["Space Exploration", "Technology"],
        "likes": 80,
        "comments": 12
    },
    {
        "id": 223,
        "title": "AI-Powered Healthcare Diagnostics",
        "description": "Learn how AI is improving diagnostic processes in healthcare.",
        "img": "https://i.ibb.co/ngMpFBX/arts.jpg",
        "category": "Technology",
        "subcategory": "Artificial Intelligence",
        "published_date": "2023-08-24",
        "author": "Emma White",
        "tags": ["AI", "Healthcare", "Technology"],
        "likes": 110,
        "comments": 20
    },
    {
        "id": 224,
        "title": "The Internet of Things (IoT) Revolution",
        "description": "Discover the impact of IoT on our daily lives.",
        "img": "https://i.ibb.co/yPW1jtV/technology.jpg",
        "category": "Technology",
        "subcategory": "Internet of Things",
        "published_date": "2023-08-23",
        "author": "John Davis",
        "tags": ["IoT", "Technology"],
        "likes": 130,
        "comments": 22
    },
    {
        "id": 225,
        "title": "Biometrics in Security",
        "description": "Explore how biometrics is enhancing security measures.",
        "img": "https://i.ibb.co/T2s8TRp/technology22.jpg",
        "category": "Technology",
        "subcategory": "Biometrics",
        "published_date": "2023-08-22",
        "author": "Sophia Johnson",
        "tags": ["Biometrics", "Security", "Technology"],
        "likes": 100,
        "comments": 15
    }
]
